version: '3'

tasks:
  run-lb:
    vars:
      TARGETS: 'http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,http://localhost:3005'
    cmd: go run main.go --port 9000 --targets {{ .TARGETS }}
  run-targets:
    deps:
      - task: run-target
        vars: { PORT: '3001' }
      - task: run-target
        vars: { PORT: '3002' }
      - task: run-target
        vars: { PORT: '3003' }
      - task: run-target
        vars: { PORT: '3004' }
      - task: run-target
        vars: { PORT: '3005' }
  run-target:
    cmd: go run test/server.go {{ .PORT }}
